# Generated by Django 4.2 on 2024-01-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email address belongs to another user.'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
