# Generated by Django 4.2 on 2024-01-13 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Phone number belongs to another user.'}, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+\\d{5,}(\\#\\d+)?$', message='Phone must be in format: +123456789[#123].')], verbose_name='phone number'),
        ),
    ]
