# Generated by Django 4.2 on 2024-01-21 09:19

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.CustomUserManager()),
            ],
        ),
    ]
