# Generated by Django 4.2 on 2024-01-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
