# Generated by Django 4.2.10 on 2024-03-30 19:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_avatar_upload_path, verbose_name='avatar'),
        ),
    ]
