services:
  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
      - POSTGRES_DB=${DJANGO_DB_NAME}
    env_file:
      - .env
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    ports:
      - "${DJANGO_DB_PORT}:${DJANGO_DB_PORT}"

  app:
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1M"
