# Generated by Django 4.2.10 on 2024-03-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_add_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfiguration',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
