# Generated by Django 4.2.11 on 2024-05-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_orderproduct_count'),
        ('payments', '0002_rename_date_payment_paid_at_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='products.order'),
            preserve_default=False,
        ),
    ]
