# Generated by Django 4.2 on 2024-01-12 18:30

import account.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^\\+\\d{5,}(\\#\\d+)?$', message='Phone must be in format: +123456789[#123].')], verbose_name='phone number')),
                ('avatar', models.ImageField(blank=True, max_length=2097152, null=True, upload_to=account.models.get_avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'])], verbose_name='avatar')),
                ('avatar_alt', models.CharField(blank=True, max_length=100, verbose_name='avatar description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
