# Generated by Django 4.2 on 2024-01-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Email address belongs to another user.'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
