# Generated by Django 4.2 on 2024-01-22 13:10

from django.contrib.auth import get_user_model
from django.db import migrations

User = get_user_model()


def create_superuser(apps, schema_editor):
    User.objects.create_superuser(username='admin', email='', password='admin')


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
