# Generated by Django 4.2 on 2024-02-02 19:26

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_rating_alter_product_specifications_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='idx_category_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='idx_product_title'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(django.db.models.functions.text.Lower('title'), name='idx_product_title_lower'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='idx_product_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_product_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['count'], name='idx_product_count'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['date'], name='idx_product_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['free_delivery'], name='idx_product_free_delivery'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating'], name='idx_product_rating'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['archived'], name='idx_product_archived'),
        ),
    ]
