# Generated by Django 4.2 on 2024-02-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_limited_edition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='limited_edition',
            new_name='is_limited_edition',
        ),
        migrations.AddField(
            model_name='product',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
