# Generated by Django 4.2.10 on 2024-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_idx_product_is_limited_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
