# Generated by Django 4.2.10 on 2024-03-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_idx_product_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='idx_category_parent',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='idx_category_title'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date_from'], name='idx_sale_date_from'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date_to'], name='idx_sale_date_to'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_price'], name='idx_sale_sale_price'),
        ),
    ]
