# Generated by Django 4.2.10 on 2024-02-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_basket_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketproduct',
            unique_together={('basket', 'product')},
        ),
    ]
