# Generated by Django 4.2.10 on 2024-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_order_delivery_type_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('', ''), ('ordinary', 'ordinary'), ('express', 'express')], max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('', ''), ('online', 'online'), ('someone', 'someone')], max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('new', 'new'), ('accepted', 'accepted')], default='new', max_length=15),
        ),
    ]
