# Generated by Django 4.2.10 on 2024-03-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_rename_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['archived'], name='idx_category_archived'),
        ),
    ]
