# Generated by Django 4.2.10 on 2024-03-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_category_idx_category_archived'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_product_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='idx_product_created_at'),
        ),
    ]
