# Generated by Django 4.2.10 on 2024-03-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_category_idx_category_parent_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['full_name'], name='idx_order_full_name'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['address'], name='idx_order_address'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['city'], name='idx_order_city'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='idx_order_email'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone'], name='idx_order_phone'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_cost'], name='idx_order_total_cost'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_type'], name='idx_order_delivery_type'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_type'], name='idx_order_payment_type'),
        ),
    ]
