# Generated by Django 4.2.11 on 2024-04-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_order_idx_order_full_name_order_idx_order_address_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['last_accessed'], name='idx_basket_last_accessed'),
        ),
    ]
