# Generated by Django 4.2.11 on 2024-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_order_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
