# Generated by Django 4.2.11 on 2024-05-08 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_product_free_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
