# Generated by Django 4.2.11 on 2024-05-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_orderproduct_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('name', 'value')},
        ),
    ]
